import {dateKey,hour,groupBy,topEntries} from "./utils.js";
export function computeStats(data){
 const {spotify,household,india}=data; const all=[...spotify,...household,...india];
 const artists={}; const tracks={}; const categories={}; const sources={spotify:spotify.length,household:household.length,india:india.length}; const days={}; const hours=Array(24).fill(0); const spend={}; const locations={};
 for(const r of spotify){artists[r.artist]=(artists[r.artist]||0)+1;tracks[r.title]=(tracks[r.title]||0)+1;hours[hour(r)]=(hours[hour(r)]||0)+1;days[dateKey(r)]=(days[dateKey(r)]||0)+1}
 for(const r of [...household,...india]){const c=r.category||"Other";categories[c]=(categories[c]||0)+1;if(r.amount!=null&&r.flow!=="Income")spend[c]=(spend[c]||0)+Number(r.amount);const loc=r.city||r.state||"Unknown";locations[loc]=(locations[loc]||0)+1;hours[hour(r)]=(hours[hour(r)]||0)+1;days[dateKey(r)]=(days[dateKey(r)]||0)+1}
 const totalSpend=[...household,...india].reduce((a,r)=>a+(r.amount&&r.flow!=="Income"?Number(r.amount):0),0);
 const skipped=spotify.filter(r=>r.skipped).length; const shuffle=spotify.filter(r=>r.shuffle).length;
 return {total:all.length,spotify:spotify.length,transactions:household.length+india.length,artists,tracks,categories,sources,days,hours,spend,locations,totalSpend,skipped,shuffle,topArtists:topEntries(artists,8),topTracks:topEntries(tracks,8),topCategories:topEntries(categories,8),topLocations:topEntries(locations,8),activeHours:hours.map((v,i)=>({hour:i,count:v}))};
}
export function buildThreads(data){
 const {spotify,household,india}=data; const purchase=[...household,...india]; const musicByDay=groupBy(spotify,r=>dateKey(r)); const purchaseByDay=groupBy(purchase,r=>dateKey(r)); const threads=[];
 const days=new Set([...musicByDay.keys(),...purchaseByDay.keys()]);
 for(const day of days){const music=musicByDay.get(day)||[];const buys=purchaseByDay.get(day)||[];if(music.length&&buys.length){threads.push({id:`t-${day}`,date:day,score:Math.min(100,40+Math.min(30,music.length/3)+Math.min(30,buys.length*4)),music:music.slice(0,4),purchases:buys.slice(0,4),title:music.length>5?"A Music-Heavy Day":"Music Meets Everyday Life",reason:`${music.length} listening events and ${buys.length} transaction records share the same date.`})}}
 const byLocation=groupBy(purchase,r=>r.city||r.state||""); for(const [loc,rows] of byLocation){if(!loc||rows.length<4)continue;threads.push({id:`l-${loc}`,date:"",score:Math.min(100,45+rows.length),music:[],purchases:rows.slice(0,8),title:`A Familiar Place: ${loc}`,reason:`${rows.length} transaction receipts are associated with ${loc}.`})}
 return threads.sort((a,b)=>b.score-a.score).slice(0,40);
}
export function buildInsights(stats,threads){const out=[];const topA=stats.topArtists[0],topC=stats.topCategories[0],topL=stats.topLocations[0],peak=stats.activeHours.reduce((a,b)=>b.count>a.count?b:a,{count:-1});if(topA)out.push({icon:"Music2",title:"A Signature Artist",metric:`${topA[1].toLocaleString()} plays`,text:`${topA[0]} is the most repeated artist in the Spotify history.`});if(peak)out.push({icon:"Clock3",title:"Your Peak Hour",metric:`${String(peak.hour).padStart(2,"0")}:00`,text:`Across the three datasets, this hour contains the highest volume of recorded activity.`});if(topC)out.push({icon:"ShoppingBag",title:"Spending Theme",metric:topC[1].toLocaleString(),text:`${topC[0]} is the most frequent transaction category in the transaction datasets.`});if(topL)out.push({icon:"MapPin",title:"A Familiar Region",metric:topL[0],text:`${topL[1].toLocaleString()} transaction records are associated with this location field.`});if(stats.skipped)out.push({icon:"SkipForward",title:"Skip Pattern",metric:`${Math.round(stats.skipped/stats.spotify*100)}%`,text:`That share of Spotify records is marked as skipped.`});if(threads.length)out.push({icon:"Network",title:"Hidden Threads",metric:`${threads.length}`,text:`Cross-dataset threads were discovered using shared dates and repeated transaction locations.`});return out}
